import type { CategoryDef } from '@/types'

export const DEFAULT_CATEGORIES: CategoryDef[] = [
  {
    id: 'inkomster',
    name: 'Inkomster',
    type: 'income',
    color: '#22c55e',
    icon: 'TrendingUp',
    subcategories: [
      { id: 'lon', name: 'Lön', parentId: 'inkomster' },
      { id: 'bidrag', name: 'Bidrag & ersättning', parentId: 'inkomster' },
      { id: 'ranteintakt', name: 'Ränteintäkter', parentId: 'inkomster' },
      { id: 'hyresintakt', name: 'Hyresintäkter', parentId: 'inkomster' },
      { id: 'ovriga-inkomster', name: 'Övriga inkomster', parentId: 'inkomster' },
    ],
  },
  {
    id: 'boende',
    name: 'Boende',
    type: 'expense',
    color: '#f59e0b',
    icon: 'Home',
    subcategories: [
      { id: 'hyra-bolan', name: 'Hyra/Bolån', parentId: 'boende' },
      { id: 'el', name: 'El', parentId: 'boende' },
      { id: 'vatten-avlopp', name: 'Vatten & avlopp', parentId: 'boende' },
      { id: 'internet-tv', name: 'Internet & TV', parentId: 'boende' },
      { id: 'hemforsäkring', name: 'Hemförsäkring', parentId: 'boende' },
      { id: 'brf-avgift', name: 'BRF-avgift', parentId: 'boende' },
      { id: 'ovriga-boende', name: 'Övriga boendekostnader', parentId: 'boende' },
    ],
  },
  {
    id: 'mat-dryck',
    name: 'Mat & Dryck',
    type: 'expense',
    color: '#ef4444',
    icon: 'ShoppingCart',
    subcategories: [
      { id: 'matvaror', name: 'Matvaror', parentId: 'mat-dryck' },
      { id: 'restaurang', name: 'Restaurang', parentId: 'mat-dryck' },
      { id: 'kafe', name: 'Kafé & fika', parentId: 'mat-dryck' },
      { id: 'takeaway', name: 'Takeaway & delivery', parentId: 'mat-dryck' },
    ],
  },
  {
    id: 'transport',
    name: 'Transport',
    type: 'expense',
    color: '#8b5cf6',
    icon: 'Car',
    subcategories: [
      { id: 'kollektivtrafik', name: 'Kollektivtrafik', parentId: 'transport' },
      { id: 'drivmedel', name: 'Drivmedel', parentId: 'transport' },
      { id: 'bilforsäkring', name: 'Bilförsäkring', parentId: 'transport' },
      { id: 'fordonsservice', name: 'Service & reparation', parentId: 'transport' },
      { id: 'parkering', name: 'Parkering', parentId: 'transport' },
      { id: 'fordonsskatt', name: 'Fordonsskatt', parentId: 'transport' },
      { id: 'taxi', name: 'Taxi', parentId: 'transport' },
    ],
  },
  {
    id: 'halsa',
    name: 'Hälsa',
    type: 'expense',
    color: '#06b6d4',
    icon: 'Heart',
    subcategories: [
      { id: 'sjukvard', name: 'Sjukvård & tandvård', parentId: 'halsa' },
      { id: 'apotek', name: 'Apotek', parentId: 'halsa' },
      { id: 'traning', name: 'Träning & gym', parentId: 'halsa' },
    ],
  },
  {
    id: 'noje-fritid',
    name: 'Nöje & Fritid',
    type: 'expense',
    color: '#f97316',
    icon: 'Music',
    subcategories: [
      { id: 'streaming', name: 'Streaming & prenumerationer', parentId: 'noje-fritid' },
      { id: 'spel', name: 'Spel & appar', parentId: 'noje-fritid' },
      { id: 'hobby', name: 'Hobby', parentId: 'noje-fritid' },
      { id: 'evenemang', name: 'Evenemang & bio', parentId: 'noje-fritid' },
      { id: 'semester', name: 'Semester & resor', parentId: 'noje-fritid' },
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    type: 'expense',
    color: '#ec4899',
    icon: 'Package',
    subcategories: [
      { id: 'klader-skor', name: 'Kläder & skor', parentId: 'shopping' },
      { id: 'elektronik', name: 'Elektronik', parentId: 'shopping' },
      { id: 'hem-inredning', name: 'Hem & inredning', parentId: 'shopping' },
      { id: 'ovriga-shopping', name: 'Övrigt shopping', parentId: 'shopping' },
    ],
  },
  {
    id: 'barn-familj',
    name: 'Barn & Familj',
    type: 'expense',
    color: '#84cc16',
    icon: 'Users',
    subcategories: [
      { id: 'barnomsorg', name: 'Barnomsorg', parentId: 'barn-familj' },
      { id: 'barnklader', name: 'Barnkläder & leksaker', parentId: 'barn-familj' },
      { id: 'skola', name: 'Skola & aktiviteter', parentId: 'barn-familj' },
    ],
  },
  {
    id: 'ekonomi',
    name: 'Ekonomi & Lån',
    type: 'expense',
    color: '#64748b',
    icon: 'PiggyBank',
    subcategories: [
      { id: 'ranta-lan', name: 'Låneränta', parentId: 'ekonomi' },
      { id: 'amortering', name: 'Amortering', parentId: 'ekonomi' },
      { id: 'forsäkring', name: 'Försäkring', parentId: 'ekonomi' },
      { id: 'avgifter', name: 'Bankavgifter & övrigt', parentId: 'ekonomi' },
    ],
  },
  {
    id: 'sparande',
    name: 'Sparande & Investering',
    type: 'savings',
    color: '#14b8a6',
    icon: 'TrendingUp',
    subcategories: [
      { id: 'buffertspar', name: 'Buffert', parentId: 'sparande' },
      { id: 'isk', name: 'ISK & aktier', parentId: 'sparande' },
      { id: 'pension', name: 'Privat pension', parentId: 'sparande' },
      { id: 'ovriga-spar', name: 'Övrigt sparande', parentId: 'sparande' },
    ],
  },
  {
    id: 'ovrigt',
    name: 'Övrigt',
    type: 'expense',
    color: '#94a3b8',
    icon: 'MoreHorizontal',
    subcategories: [
      { id: 'gaver', name: 'Gåvor & välgörenhet', parentId: 'ovrigt' },
      { id: 'husdjur', name: 'Husdjur', parentId: 'ovrigt' },
      { id: 'utbildning', name: 'Utbildning & kurser', parentId: 'ovrigt' },
      { id: 'ovrigt-ovrigt', name: 'Övrigt', parentId: 'ovrigt' },
    ],
  },
]
